#!/usr/bin/python3

import sys
import math

def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

def factorize_rsa_number(n):
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0 and is_prime(i) and is_prime(n // i):
            return i, n // i
    return None, None

def main(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            n = int(line.strip())
            p, q = factorize_rsa_number(n)
            if p is not None and q is not None:
                print("{}={}*{}".format(n, p, q))

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        sys.exit(1)
    
    file_path = sys.argv[1]
    main(file_path)

